# L = [1,3,4,5, 'epita']

# # L.append(10.)

# del L[3]
# # print(L)

# L = [1,3,4,5, 'epita']

# L.extend(["epita"])
# # print(L)
# L = [1,3,4,5, 'epita']

# L.extend([0,1])
# print(L)

# l = [1, 3, 4, 5, 'epita', 0, 1]

# l[-1]
# l = [1, 3, 4, 5, 'epita', 0, 1]
def add_one(x):
    res = x + 1
    return res
x_old = 2
x_new = add_one(x_old)
print(x_new)


l = [1, 3, 4, 5, 'epita', 0, 1]
l = [1, 3, 4, 5, 'epita', 0, 1]
l = [1, 3, 4, 5, 'epita', 0, 1]

l = [1, 3, 4, 5, 'epita', 0, 1]
l = [1, 3, 4, 5, 'epita', 0, 1]
l = [1, 3, 4, 5, 'epita', 0, 1]
l = [1, 3, 4, 5, 'epita', 0, 1]
l = [1, 3, 4, 5, 'epita', 0, 1]
l = [1, 3, 4, 5, 'epita', 0, 1]
l = [1, 3, 4, 5, 'epita', 0, 1]
print(l)
l[-1].append(100)
print(l)
l.append([0,1]
l[-1][0] = -1 
l[-1] = [-1, 0, 2, 100]
[5] + l[-1]
#to add in the starting
print(l)
l[-1] =  [5] + l[-1]
print(l)
l[]
l[2,5]
l[2:5]
l[2:8]
l[2:5:2]
l[2:5:1]
l[-1][0:]
l[-1][2:-1]

ln = [0,1,3,4,5,6,7,8,9,10]
print(ln[:3])
# print(ln[3:]

print(ln[3:])
ln[:3] + ln[100] + ln[3:]
ln[:3] + ln[100] + ln[3:]
ln = [0,1,3,4,5,6,7,8,9,10]
print(len(ln))
print(max(ln))
print(min(ln))
print(sum(ln))
# check element in the list 
print( 6 in ln )
print( 1 in ln )
print( 100 in ln )
print( 50 in ln )
print( 8 in ln )
print( 6 in ln )
twodimlist = [[0,1], [2,5]]
print(twodimlist)
# dictionaries
d = {
    'x' : [[0,1], [2,5]],
    'y' : [0,1]
}
print(d['x'])

d[0]
d['x']
print(d)
d
dir(d)
d['x'][1]
d['x'][-1]
d['x'][1][0]
# test and loops 
number = 2 
if number > 0:
    print("the number is greater than zero")
    number = 2 * number
    print('lets double the number',number)
number = -1
if number > 0:
    print("the number is greater than zero")
    number = 2 * number
    print('lets double the number',number)
number = 2 
if number > 0:
    print("the number is greater than zero")
number = 2 * number
    print('lets double the number',number)
number = -1
if number > 0:
    print("the number is greater than zero")
    number = 2 * number
    print('lets double the number',number)
else:
    print("the number is negative")
number = -1
if number > 0:
    print("the number is greater than zero")
    number = 2 * number
print('lets double the number',number)
number = 5
if number > 0:
    print("the number is greater than zero")
    number = 2 * number
    print('lets double the number',number)
elif number == 0:
    print("the number is null")
else:
    print("the number is negative")

# loops 
#the for loop runs through a set
# the while loop 
for i in [1,2,3,4,5]:
    print(i ** 2)
for i in [1,2,3,4,5,6,7,8,9,10]:
    print(i+1)
for i in [ 1,2,3,4,5,6]:
    if i>2:
        print(i ** 2)
for i in [ 1,2,3,4,5,6]:
    if i>2:
        print(i ** 2)
    else:
        print(i)
for i in [ 1,2,3,4,5,6]:
    if i>2:
        print(i ** 2)
    print(i)
for i in [0,1,2,3,4,5,6]:
    print(i ** 2)
# range function
# range(stop)
 # range(start,stop,step)

for i in range(5):
    print(i ** 2)
for i in range(5,50,2):
    print(i ** 2)
for i in range(5):
    print(i ** 2)
    i = 2
for i in range(5):
    print(i ** 2)
    i += 2
# for while loops 
i = 0
while i < 10:
    i = i + 2
    print(i)
    
def add_one(x):
    res = x + 1
    return res
x_old = 2
x_new = add_one(x_old)
print(x_new)
def add(x, n):
    """
    this function adds "n" to the variable x
    """
    x = x + n
    return(x)

x_old = 2
n = 5
x_new = add(x_old, n)
print(x_new)


